name: ad_hoc_ident_util_crypto
description: "Provides hash functionalities to encrypt AdHocIdentities as part of the ad_hoc_ident framework."
version: 0.0.1-preview-1
homepage: https://github.com/FabianMoeckel/ad_hoc_ident_util_crypto
repository: https://github.com/FabianMoeckel/ad_hoc_ident_util_crypto

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  crypto: ^3.0.3
  ad_hoc_ident: ^0.0.1-preview-1

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8